# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cpf',
            field=models.IntegerField(verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rg',
            field=models.IntegerField(verbose_name='RG'),
        ),
    ]
