# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_auto_20170209_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='date',
            new_name='data',
        ),
    ]
