# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0005_auto_20170209_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.Patient', verbose_name='Nome do Paciente'),
        ),
    ]
