# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0006_auto_20170209_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='description',
        ),
        migrations.AddField(
            model_name='patient',
            name='description',
            field=models.TextField(blank=True, verbose_name='Historico'),
        ),
    ]
