# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('consulta', '0007_auto_20170210_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
