# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0008_dentist_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
