# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0010_assistente_recepcionista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistente',
            options={'ordering': ['name'], 'verbose_name': 'Assistente', 'verbose_name_plural': 'Assistentes'},
        ),
        migrations.AlterModelOptions(
            name='recepcionista',
            options={'ordering': ['name'], 'verbose_name': 'Recepcionista', 'verbose_name_plural': 'Recepcionistas'},
        ),
    ]
