# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 23:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consulta', '0011_auto_20170210_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
